name: docfx-unitypackage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          submodules: true

      - name: Checkout docfx-unitypackage Repository
        uses: actions/checkout@v4.1.2
        with:
          # 使いたいactionがあるorganization/repositoryをcheckoutする対象に指定
          repository: kochounoyume/docfx-unitypackage-supported-define
          # branch名だけでなくtagやcommit hashなど取得元を一意に特定できるものなら何でもok
	        ref: main
	        # 取得したアクションをこのリポジトリのどこのディレクトリに持ってくるか決める
          path: .github/actions/other-repository

      - name: Build
        uses: ./.github/actions/other-repository
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
