name: Publish source generator project to Github Packages
on:
  push:
    branches:
    - main
    paths:
    - src/MinimalUtility.SourceGenerator/**
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore src/MinimalUtility.SourceGenerator/MinimalUtility.SourceGenerator.csproj
      - run: dotnet build src/MinimalUtility.SourceGenerator/MinimalUtility.SourceGenerator.csproj --configuration Release
      - run: dotnet pack src/MinimalUtility.SourceGenerator/MinimalUtility.SourceGenerator.csproj  --configuration Release -o src/MinimalUtility.SourceGenerator/artifacts/
      - run: dotnet nuget add source --username kochounoyume --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kochounoyume/index.json"
      - run: dotnet nuget push src/MinimalUtility.SourceGenerator/artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/kochounoyume/index.json --skip-duplicate
