name: Meta File Check (github-hosted ubuntu-latest)
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - Assets/*
      - Packages/*

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v2
        with:
          submodules: false
          lfs: true

      - name: Unity meta files check (github-hosted ubuntu-latest)
        uses: DeNA/unity-meta-check@v3.2.2